/**:
  ros__parameters:
    robot_description_kinematics:
      arm:  # SRDF의 그룹명과 동일해야 함
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.1
        position_only_ik: false
        root: base_link
        tip: tcp
